---
title: Блок «Catch», никогда не достигнут, поскольку "<name1>«наследует от»<name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 59dfa9cbc80bc9cc3faf07923d0d579070750426
ms.sourcegitcommit: bef803e2025642df39f2f1e046767d89031e0304
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/15/2019
ms.locfileid: "56305978"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Блок «Catch», никогда не достигнут, поскольку "\<Имя1 >" наследует от "\<имя2 >"
Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также

- [Как использовать блок try/catch для перехвата исключений](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
