---
title: "Блок &quot;Catch&quot;, никогда не будет достигнут, поскольку &quot;&lt;name1&gt;«наследует от»&lt;name2&gt;&quot; | Документы Microsoft"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
caps.latest.revision: 12
author: stevehoag
ms.author: shoag
translation.priority.ht:
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- ru-ru
- zh-cn
- zh-tw
translation.priority.mt:
- cs-cz
- pl-pl
- pt-br
- tr-tr
translationtype: Machine Translation
ms.sourcegitcommit: a06bd2a17f1d6c7308fa6337c866c1ca2e7281c0
ms.openlocfilehash: 2c7f180b2221b5aa6814629a5a8cd9b9d7f9fb1b
ms.lasthandoff: 03/13/2017

---
# <a name="39catch39-block-never-reached-because-39ltname1gt39-inherits-from-39ltname2gt39"></a>Блок 'Catch', никогда не будет достигнут, поскольку "&lt;name1&gt;«наследует от»&lt;name2&gt;"
Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [в Visual Basic](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также  
 [Практическое руководство: тестирование кода с помощью блока Try... Блок catch в Visual Basic](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)   
 [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
