---
title: Блок «Catch», никогда не достигнут, поскольку "&lt;name1&gt;«наследует от»&lt;name2&gt;"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 7a51857bf2f181224c64a4295001e5ea24474cdb
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/22/2018
ms.locfileid: "53767482"
---
# <a name="catch-block-never-reached-because-ltname1gt-inherits-from-ltname2gt"></a>Блок «Catch», никогда не достигнут, поскольку "&lt;name1&gt;«наследует от»&lt;name2&gt;"
Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также  
 [Практическое руководство. Проверка кода с помощью Try... Блок catch в Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
