---
title: Блок «Catch», никогда не достигнут, поскольку "<name1>«наследует от»<name2>"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 89b916513633515ce5433d06e4cdda7039c688c3
ms.sourcegitcommit: 14355b4b2fe5bcf874cac96d0a9e6376b567e4c7
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 01/30/2019
ms.locfileid: "55289618"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Блок «Catch», никогда не достигнут, поскольку "\<Имя1 >" наследует от "\<имя2 >"
Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также
- [Практическое руководство. Проверка кода с помощью Try... Блок catch в Visual Basic](https://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)
- [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
