---
title: "2576 - TryCatchExceptionFromTry | Microsoft Docs"
ms.custom: ""
ms.date: "03/30/2017"
ms.prod: ".net-framework"
ms.reviewer: ""
ms.suite: ""
ms.tgt_pltfrm: ""
ms.topic: "article"
ms.assetid: 47e48973-b17c-4a16-8338-c84b54aa0a6e
caps.latest.revision: 2
author: "Erikre"
ms.author: "erikre"
manager: "erikre"
caps.handback.revision: 2
---
# 2576 - TryCatchExceptionFromTry
## Свойства  
  
|||  
|-|-|  
|Идентификатор|2576|  
|Ключевые слова|WFActivities|  
|Уровень|Сведения|  
|Канал|Microsoft\-Windows\-Application Server\-Applications\/Debug|  
  
## Описание  
 Показывает, что действие TryCatch перехватило исключение.  
  
## Сообщение  
 В действии TryCatch «%1» было перехвачено исключение типа «%2».  
  
## Подробные сведения  
  
|Имя элемента данных|Тип элемента данных|Описание|  
|-------------------------|-------------------------|--------------|  
|DisplayName|xs:string|Отображаемое имя действия.|  
|Исключение|xs:string|Имя типа исключения.|  
|AppDomain|xs:string|Строка, возвращаемая AppDomain.CurrentDomain.FriendlyName.|